// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_8x8 = "CgkI_r7csJobEAIQBg"; // <GPGSID>
        public const string leaderboard_5x5 = "CgkI_r7csJobEAIQBA"; // <GPGSID>
        public const string achievement_8192 = "CgkI_r7csJobEAIQDg"; // <GPGSID>
        public const string leaderboard_6x6 = "CgkI_r7csJobEAIQBQ"; // <GPGSID>
        public const string achievement_nothing_is_impossible = "CgkI_r7csJobEAIQCQ"; // <GPGSID>
        public const string achievement_16_k = "CgkI_r7csJobEAIQDw"; // <GPGSID>
        public const string achievement_524_k = "CgkI_r7csJobEAIQFA"; // <GPGSID>
        public const string achievement_262_k = "CgkI_r7csJobEAIQEw"; // <GPGSID>
        public const string achievement_4096 = "CgkI_r7csJobEAIQDQ"; // <GPGSID>
        public const string leaderboard_3x3 = "CgkI_r7csJobEAIQAg"; // <GPGSID>
        public const string achievement_a_small_genius = "CgkI_r7csJobEAIQCg"; // <GPGSID>
        public const string achievement_one_million_tile = "CgkI_r7csJobEAIQFQ"; // <GPGSID>
        public const string achievement_131_k = "CgkI_r7csJobEAIQEg"; // <GPGSID>
        public const string achievement_1_k = "CgkI_r7csJobEAIQCw"; // <GPGSID>
        public const string achievement_32_k = "CgkI_r7csJobEAIQEA"; // <GPGSID>
        public const string leaderboard_4x4 = "CgkI_r7csJobEAIQAw"; // <GPGSID>
        public const string achievement_a_new_2048 = "CgkI_r7csJobEAIQDA"; // <GPGSID>
        public const string achievement_65_k = "CgkI_r7csJobEAIQEQ"; // <GPGSID>
        public const string achievement_a_little_step = "CgkI_r7csJobEAIQBw"; // <GPGSID>
        public const string achievement_exploit = "CgkI_r7csJobEAIQCA"; // <GPGSID>

}

